### ISSUE TITLE
Create a new materialization insert_by_period 

### ISSUE THREAD

**Issue by nicor88** [dbt-labs/dbt-athena#190]
Inspired by https://gist.github.com/jessedobbelaere/6fdb593f9e2cc732e9f142c56c9bac87
create a new materialisation: insert_by_period.

## Requirements
* Support table_type=hive
* Support for table_type=iceberg
  * to make the implementation idempotent add `delete from table period={period_to_process}` to avoid duplicates in case some error occur

**Comment by svdimchenko** [comment]
@nicor88 WDYT is this materialisation still needed ? I believe this commit resolves huge source datasets processing.

**Comment by nicor88** [comment]
@svdimchenko yes, I believe that is still needed.

**Comment by nicor88** [comment]
@svdimchenko for more context on my last message see this one https://github.com/dbt-athena/dbt-athena/issues/471

**Comment by mycaule** [comment]
You should support also [`unique_key`](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional), I don't think the gist code has any way to deal with that.

**Comment by nicor88** [comment]
@mycaule why unique_key should included in insert_by_period? Insert by period by definition acts on time, and it delete insert batches of periods. If you need to do upsert by unique_key maybe you consider to use an incremental materialization with merge strategy and of course unique_key.

**Comment by mycaule** [comment]
Using incremental fails for large tables as you discussed in https://github.com/dbt-athena/dbt-athena/issues/471
and the snippet from redshift provided in the discussion was the only quick way to do it in my case.

**Comment by nicor88** [comment]
Which snippet for redshift? Do you mean this https://github.com/dbt-athena/dbt-athena/issues/471#issuecomment-1790572382 ? if so I don't see any reference to unique_key.

Also:

```
config(materialized='incremental', unique_key='id', force_batch=True))
```
that is incomplete, that is your default `incremental_strategy`? I assume merge if you use unique_key.

**Comment by mycaule** [comment]
This snippet talks about Redshift and adapting to Athena: https://gist.github.com/jessedobbelaere/6fdb593f9e2cc732e9f142c56c9bac87

For the moment I use the default `incremental_strategy` which should be `append`, using Hive format for the moment because of legacy. For the `merge` strategy to work I would have to move to Iceberg.

**Comment by mycaule** [comment]
Let's imagine I stay with Hive, I understand that to be able to be able to use `insert_overwrite`, the `partitioned_by` field is mandatory

Do you think I can do `partitioned_by=['bucket(id, 100)']` to both stay within the 100 partitions limit, and only rewrite on average O(N/100) of my data.

**Comment by jessedobbelaere** [comment]
💡 Last night, dbt made [this announcement about a new incremental-strategy for time-series event data](https://github.com/dbt-labs/dbt-core/discussions/10672). It introduces `incremental_strategy='microbatch'` to enable micro-batching to replace the custom insert-by-period macro's in the wild. It also seems to simplify things a lot, less config and including sampling for dev runs. Let's focus on integrating with this feature when it comes out?

**Comment by nicor88** [comment]
@jessedobbelaere we should indeed consider to support the microbatch in dbt-athena.
We should consider to create another issue to track incremental_strategy microbatch, and closing eventually this one.

**Comment by jessedobbelaere** [comment]
Exactly 👍 I've created #715 as placeholder

**Comment by amychen1776** [comment]
Hi folks - our team is already looking at supporting our new Microbatch strategy on this adapter so for now, we are going to go ahead and close out this issue since this will address this issue :)
