### ISSUE TITLE
Standard GitHub issue and PR templates

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-athena#739]
### Is this your first time submitting an issue in dbt-athena?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature

### Describe your request/question

For standardization across adapter repos managed by dbt Labs, the issue and PR templates from [here](https://github.com/dbt-labs/dbt-snowflake/tree/main/.github) should also be in this repo.

### Tasklist
- [ ] [Issue templates](https://github.com/dbt-labs/dbt-snowflake/tree/main/.github/ISSUE_TEMPLATE)
- [ ] [PR template](https://github.com/dbt-labs/dbt-snowflake/blob/main/.github/pull_request_template.md)

**Comment by amychen1776** [comment]
Closing this because I just implemented it
